- name: Pulling Server inventory Data for given server
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    uuid: "{{ UUID ] }}"
    command_options: nodes
  register: nodes_data
  tags: gather_server_facts

- name: Set Ansible Facts with nodes Data
  set_fact: "{{ nodes_data.result }}"
  tags: gather_server_facts

- name: Update custom facts
  template: src=myfacts.txt.j2 dest=/etc/ansible/facts.d/{{ UUID }}.fact
  tags: gather_server_facts