# Task file for lenovo.lxca-compliance role
# This task pull the server inventory Data from LXCA and store it in custom facts

- name: Reading Compliance Rules
  include_vars:
    file: compliance_rules.yml
    name: comp_rules_dict
  tags: gather_server_facts,validate_server_facts

- include: collect_server_inventory.yml
  with_items: "{{ comp_rules_dict['Servers'] }}"
  tags: gather_server_facts


#- name: Filtering facts
#  set_fact:
#    node_list: "{{ node_list|default([]) | union([{ 'uuid': item.uuid, 'machineType': item.machineType }]) }}"
#  when:
#    - item.uuid == server_uuid
#  with_items: "{{ rslt.result.nodeList}}"
#  tags:
#    gather_server_facts

#- name: Update custom facts
#  template: src=myfacts.txt.j2 dest=/etc/ansible/facts.d/{{item.uuid}}.fact
#  with_items: "{{ node_list }}"
#  tags:
#    gather_server_facts

#- name: Print Ansible Facts
#  debug:
#    msg: ansible_facts
#  tags:
#    gather_server_facts