---
- include: validate_basic_compliance.yml
- include: validate_config_compliance.yml
#- include: validate_plugin_compliance.yml

#- name: Call Compliance Engine
#  pylxca_module:
#    login_user: "{{ lxca_user }}"
#    login_password: "{{ lxca_password }}"
#    auth_url: "{{ lxca_url }}"
#    command_options: compliance_engine
#  register: rslt
#  tags:
#     compliance