# Task file for lenovo.lxca-compliance role
# This task will read custom fact and validate them against compliance rule

#Gatherer code for Complance Engine for Basic Rule Validation
#This code is responsible for gathering inventory data for given Endpoint


#- debug:
#    msg: "Resource value = {{ RESOURCE_TYPE }}"
#  tags: validate_basic_server_facts


#===========================================
#TODO Read Rule content and pull out source and execute gatherer code for each source
#===========================================

- name: Pulling Server inventory Data for given server
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    uuid: "{{ resource_uuid }}"
    command_options: nodes
  register: nodes_data
  tags: gather_server_facts

- name: dumping data in to fact file
  copy:
    content: "{{ nodes_data.result }}"
    dest: /etc/ansible/facts.d/{{RESOURCE_UUID}}.fact
  tags: gather_server_facts

#============================================

- name: Reload the facts
  setup: ~
  tags: validate_server_facts

- name: Validating Compliance Rules for given Server
  vars:
    uuid: "{{ resource_uuid }}"
  pylxca_module:
    rule_content: "{{ rule_content }}"
    inv_data: "{{ ansible_local[ uuid ] }}"
    command_options: validate_basic_rules
  register: result
  tags: validate_server_facts

- name: Check Validate result
  debug:
    var: result.result
  tags: validate_server_facts

- name: Return result to callee
  assert:
    that:
       -  "True==result.result"
  tags: validate_server_facts