- name: Display information about firmware from firmware-updates repository
  hosts: server1
  connection: local
#  vars:
#    key:  '{{ key }}'
  tasks:
    - name: firmware-updates repository information
      pylxca_module:
        command_options: updaterepo
        login_user: USERID
        login_password: CME44ibm
        auth_url: https://10.243.14.80
#        repo_key: '{{ key }}'
      register: firmware_info
    - debug:
        var: firmware_info
