---
# defaults file for lenovo.lxca-config
manage_user: null
manage_password: null
name: null
description: null
type: null
solutionVPD: null
members: null
criteria: null
sol_id: null
manifest_path: null
id: null
solutionGroup: null
comp_rule: null
