- name: Create a resource group for ThingAgile Solution
  pylxca_module:
    command_options: create_resourcegroups
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    resource_group_name: "{{ resource_group_name }}"
    description: "{{ description }}"
    type: "{{ type }}"
    solutionVPD: "{{ solutionVPD }}"
    members: "{{ members }}"
    criteria: "{{ criteria }}"
  register: rslt
  tags:
    create_resourcegroups
