- name: get a resource group
  pylxca_module:
    command_options: get_resourcegroups
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    uuid: "{{ uuid }}"
  register: rslt
  tags:
    get_resourcegroups
