---

# tasks file for lenovo.lxca-uhm
- name: Create a resource group for ThingAgile Solution
  pylxca_module:
    command_options: create_resourcegroups
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    name: "{{ name }}"
    description: "{{ description }}"
    type: "{{ type }}"
    solutionVPD: "{{ solutionVPD }}"
    members: "{{ members }}"
    criteria: "{{ criteria }}"
  register: rslt
  tags:
    create_resourcegroups

- name: get a resource group
  pylxca_module:
    command_options: create_resourcegroups
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    uuid: "{{ uuid }}"
  register: rslt
  tags:
    get_resourcegroups

- name: Add a member to resource group for ThingAgile Solution
  pylxca_module:
    command_options: add_resourcegroup_member
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    name: "{{ name }}"
    members: "{{ members }}"
  register: rslt
  tags:
    add_group_member

- name: send solution manifest to LXCA
  pylxca_module:
    command_options: manifests
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    sol_id: "{{ sol_id }}"
    manifest_path: "{{ manifest_path }}"
  register: rslt
  tags:
    manifest

- name: Reading rules from file
  include_vars:
    file: compliance_rules.yaml
    name: rules
  tags: import_compliance_rules

- name: Show variables read
  debug:
    var: rules.rules[1]
  tags: import_compliance_rules


- name: Importing compliance rules on LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    comp_rule: "{{ item }}"
    command_options: rules
  register: rslt
  with_items: "{{ rules.rules }}"
  tags: import_compliance_rules


- name: get compliance rules from LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    id: "{{ id }}"
    command_options: rules
  register: rslt
  tags: get_compliance_rules


- name: Updating composite results on LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    solutionGroups: "{{ solutionGroups }}"
    command_options: compositeResults
  register: rslt
  tags: update_solutionGroup_compositeResults

- name: Updating composite results on LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    targetResources: "{{ targetResources }}"
    command_options: compositeResults
  register: rslt
  tags: update_targetResources_compositeResults

- name: Updating composite results on LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    all_rules: true
    command_options: compositeResults
  register: rslt
  tags: process_all_rules_compositeResults

- name: get composite results on LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    id: "{{ id }}"
    command_options: compositeResults
  register: rslt
  tags: get_compositeResults

- name: query solution group composite results on LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    query_solutionGroups: "{{ query_solutionGroups }}"
    command_options: compositeResults
  register: rslt
  tags: query_solutionGroup_compositeResults
