---
# tasks file for lenovo.lxca-uhm
- import_tasks: create_resourcegroups.yml
- import_tasks: get_resourcegroups.yml
- import_tasks: add_group_members.yml
- import_tasks: manifest.yml
- import_tasks: import_compliance_rules.yml
- import_tasks: get_compliance_rules.yml
- import_tasks: update_solutionGroup_compositeResults.yml
- import_tasks: update_targetResources_compositeResults.yml
- import_tasks: process_all_rules_compositeresults.yml
- import_tasks: get_compositeresults.yml
- import_tasks: query_solutionGroup_compositeresults.yml
