---

# tasks file for lenovo.lxca-uhm
- name: Create a resource group for ThingAgile Solution
  pylxca_module:
    command_options: create_resourcegroups
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    group_name: "{{ group_name }}"
    group_desc: "{{ group_desc }}"
    group_type: "{{ group_type }}"
    solutionVPD: "{{ solutionVPD }}"
    group_members: "{{ group_members }}"
    group_criteria: "{{ group_criteria }}"
  register: rslt
  tags:
    create_group

- name: Add a member to resource group for ThingAgile Solution
  pylxca_module:
    command_options: add_resourcegroup_member
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    group_name: "{{ group_name }}"
    group_members: "{{ group_members }}"
  register: rslt
  tags:
    add_group_member

- name: send solution manifest to LXCA
  pylxca_module:
    command_options: manifests
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    sol_id: "{{ sol_id }}"
    manifest_path: "{{ manifest_path }}"
  register: rslt
  tags:
    manifest

