---

# tasks file for lenovo.lxca-uhm
- name: Create a resource group for ThingAgile Solution
  pylxca_module:
    command_options: create_resourcegroups
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    name: "{{ name }}"
    description: "{{ description }}"
    type: "{{ type }}"
    solutionVPD: "{{ solutionVPD }}"
    members: "{{ members }}"
    criteria: "{{ criteria }}"
  register: rslt
  tags:
    create_resourcegroups

- name: get a resource group
  pylxca_module:
    command_options: create_resourcegroups
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    uuid: "{{ uuid }}"
  register: rslt
  tags:
    get_resourcegroups

- name: Add a member to resource group for ThingAgile Solution
  pylxca_module:
    command_options: add_resourcegroup_member
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    name: "{{ name }}"
    members: "{{ members }}"
  register: rslt
  tags:
    add_group_member

- name: send solution manifest to LXCA
  pylxca_module:
    command_options: manifests
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    sol_id: "{{ sol_id }}"
    manifest_path: "{{ manifest_path }}"
  register: rslt
  tags:
    manifest

