- name: Updating composite results on LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    targetResources: "{{ targetResources }}"
    command_options: compositeResults
  register: rslt
  tags: update_targetresources_compositeresults

