---
# defaults file for lenovo.lxca-config
lxca-config_version: "0.1"
uuid: null
id: null
endpoint_ip: null
user: null
password: null
recovery_password: null
jobid: null
mode: null
action: null
server: null
switch: null
storage: null
cmm: null
force: null
policy_info: null
policy_name: null
policy_type: null
jobid: null