- name: List all CMMS of Managed chassis from LXCA
  hosts: localhost 
  connection: local
  tasks:
    - name: cmms
      pylxca_module:
        login_user: "{{ lxca_user }}"
        login_password: "{{ lxca_password }}"
        auth_url: "{{ lxca_url }}"
        command_options: chassis
      register: rslt 
    - debug:
        var: rslt 

