---
# tasks file for lenovo.lxca-config
- name: get configpatterns data from LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    command_options: configpatterns
  register: rslt
  tags:
     configpatterns

- name: get configprofiles data from LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    id: "{{ id }}"
    command_options: configprofiles
  register: rslt
  tags:
     configprofiles


- name: get configtargets data from LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    id: "{{ id }}"
    command_options: configtargets
  register: rslt
  tags:
     configtargets

- block:
  - name: Manage given endpoint
    pylxca_module:
      login_user: "{{ lxca_user }}"
      login_password: "{{ lxca_password }}"
      auth_url: "{{ lxca_url }}"
      endpoint_ip: "{{ endpoint_ip }}"
      user: "{{ user }}"
      password: "{{ password }}"
      recovery_password: "{{ recovery_password }}"
      force: "{{ force }}"
      command_options: manage
    register: rslt_job
  - debug:
      var: rslt_job
  - assert:
      that:
        - " 'Success' in rslt_job.msg"

  - name: Polling for Status of Manage Operation
    pylxca_module:
      command_options: manage_status
      login_user: "{{ lxca_user }}"
      login_password: "{{ lxca_password }}"
      auth_url: "{{ lxca_url }}"
      jobid: "{{ rslt_job.result }}"
    register: result
    until: result.result.progress == 100.0
    retries: 20
    delay: 15

  - debug:
      var: result.result.progress
  tags:
    manage

- name: get updaterepo data from LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    repo_key: "{{ repo_key }}"
    command_options: updaterepo
  register: rslt
  tags:
     updaterepo

- name: get updatecomp data from LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    update_mode: "{{ update_mode}}"
    update_action: "{{ update_action }}"
    update_server: "{{ update_server }}"
    command_options: updatecomp
  register: rslt
  tags:
     updatecomp