---
# tasks file for lenovo.lxca-config
- import_tasks: query_update_comp.yml
- import_tasks: update_firmware_all.yml

- name: Checking for pattern from file
  include_vars:
    file: config_pattern_import.yml
    name: pattern_update_dict
  when: pattern_from_file == 'true'
  tags: import_configpatterns


- name: Importing configpatterns on LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    pattern_update_dict: "{{ pattern_update_dict }}"
    command_options: import_configpatterns
  register: rslt
  tags: import_configpatterns

- name: get configpatterns data from LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    id: "{{ id }}"
    name: "{{ name }}"
    endpoint: "{{ endpoint }}"
    restart: "{{ restart }}"
    type: "{{ type }}"
    command_options: apply_configpatterns
  register: rslt
  tags:
     apply_configpatterns

- name: get configpatterns data from LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    command_options: get_configpatterns
  register: rslt
  tags:
     get_configpatterns

- name: get configpatterns data from LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    id: "{{ id }}"
    includeSettings: "{{ includeSettings }}"
    command_options: get_particular_configpattern
  register: rslt
  tags:
     get_particular_configpattern

- name: get configstatus data from LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    endpoint: "{{ endpoint }}"
    status: "{{ status }}"
    command_options: get_configstatus
  register: rslt
  tags:
    get_configstatus

- name: get configprofiles data from LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    id: "{{ id }}"
    name: "{{ name }}"
    endpoint: "{{ endpoint}}"
    restart: "{{ restart }}"
    action: "{{ action }}"
    powerdown: "{{ powerdown }}"
    resetimm: "{{ resetimm }}"
    force: "{{ force }}"
    command_options: configprofiles
  register: rslt
  tags:
     configprofiles


- name: get configtargets data from LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    id: "{{ id }}"
    command_options: configtargets
  register: rslt
  tags:
     configtargets

- block:
  - name: Managing given endpoint
    pylxca_module:
      login_user: "{{ lxca_user }}"
      login_password: "{{ lxca_password }}"
      auth_url: "{{ lxca_url }}"
      endpoint_ip: "{{ endpoint_ip }}"
      user: "{{ user }}"
      password: "{{ password }}"
      recovery_password: "{{ recovery_password }}"
      force: "{{ force }}"
      command_options: manage
    register: rslt_job
  - debug:
      var: rslt_job
  - name: Check manage job submission
    assert:
      that:
       -  " 'Success' in rslt_job.msg"

  - name: Polling for Status of Manage Operation
    pylxca_module:
      command_options: manage_status
      login_user: "{{ lxca_user }}"
      login_password: "{{ lxca_password }}"
      auth_url: "{{ lxca_url }}"
      jobid: "{{ rslt_job.result }}"
    register: result
    until: result.result.progress == 100.0
    retries: 40
    delay: 15

  - debug:
      var: result.result.progress
      var: result.result.results[0].result

  - name: Check manage job completion
    assert:
      that:
       -  " 'SUCCESS' in result.result.results[0].result"

  tags:
    manage

- block:
  - name: Unmanaging given endpoint
    pylxca_module:
      login_user: "{{ lxca_user }}"
      login_password: "{{ lxca_password }}"
      auth_url: "{{ lxca_url }}"
      endpoint_ip: "{{ endpoint_ip }}"
      force: "{{ force }}"
      command_options: unmanage
    register: rslt_job
  - debug:
      var: rslt_job
  - name: Check submission of Unmanage job
    assert:
      that:
        - " 'Success' in rslt_job.msg"

  - name: Polling for Status of UnManage Operation
    pylxca_module:
      command_options: unmanage_status
      login_user: "{{ lxca_user }}"
      login_password: "{{ lxca_password }}"
      auth_url: "{{ lxca_url }}"
      jobid: "{{ rslt_job.result }}"
    register: result
    until: result.result.progress == 100.0
    retries: 20
    delay: 15

  - debug:
      var: result.result.progress
  tags:
    unmanage

- name: get updaterepo data from LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    repo_key: "{{ repo_key }}"
    action: "{{ action }}"
    machine_type: "{{ machine_type }}"
    scope: "{{ scope }}"
    fixids: "{{ fixids }}"
    file_type: "{{ file_type }}"
    command_options: updaterepo
  register: rslt
  tags:
     updaterepo

- name: Updating Firmware of device from LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    mode: "{{ mode}}"
    action: "{{ action }}"
    cmm: "{{ cmm }}"
    switch: "{{ switch }}"
    server: "{{ server }}"
    storage: "{{ storage }}"
    command_options: update_firmware
  register: rslt
  tags:
     update_firmware

- name: Getting Firmware Update Status from LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    command_options: update_firmware_query_status
  register: rslt
  tags:
     query_update_status

- name: Get or Apply updatepolicy to device from LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    policy_info: "{{ policy_info}}"
    policy_name: "{{ policy_name}}"
    policy_type: "{{ policy_type}}"
    uuid: "{{ uuid }}"
    jobid: "{{ jobid }}"
    command_options: updatepolicy
  register: rslt
  tags:
    updatepolicy

- name: Get or Apply osimages to device from LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    osimages_info: "{{ osimages_info }}"
    osimages_dict: "{{ osimages_dict }}"
    command_options: osimages
  register: rslt
  tags:
     osimages

- block:
  - name: Get Jobid for import file to repository of osimages
    pylxca_module:
      login_user: "{{ lxca_user }}"
      login_password: "{{ lxca_password }}"
      auth_url: "{{ lxca_url }}"
      osimages_dict: "{{ osimages_imagetype_dict }}"
      command_options: osimages
    register: rslt

  - debug:
      var: rslt.result.jobId

  - name: Check import_dict value
    set_fact:
     mod_import_dict: "{{ import_dict | combine( {'jobId' : rslt.result.jobId }) }}"

  - name: Post Job for import file to repository of osimages
    pylxca_module:
      login_user: "{{ lxca_user }}"
      login_password: "{{ lxca_password }}"
      auth_url: "{{ lxca_url }}"
      osimages_dict: "{{ mod_import_dict }}"
      command_options: osimages
    register: rslt
  tags:
    import_osimages

- block:
  - name: Get Jobid for import file to management server
    pylxca_module:
      login_user: "{{ lxca_user }}"
      login_password: "{{ lxca_password }}"
      auth_url: "{{ lxca_url }}"
      action: "{{ action }}"
      files: "{{ files }}"
      command_options: import_managementserver_pkg
    register: rslt

  - debug:
      var: rslt.result.jobid

  - name: Post Job for import files to mamagement server
    pylxca_module:
      login_user: "{{ lxca_user }}"
      login_password: "{{ lxca_password }}"
      auth_url: "{{ lxca_url }}"
      action: "{{ action }}"
      files: "{{ files }}"
      jobid: "{{ rslt.result.jobid }}"
      command_options: import_managementserver_pkg
    register: rslt
  tags:
    import_managementserver_pkg

- name: get managementserver updates on LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    update_key: "{{ update_key }}"
    command_options: get_managementserver_pkg
  register: rslt
  tags: get_managementserver_pkg

- name: get managementserver updates on LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    update_key: "{{ update_key }}"
    fixids: "{{ fixids }}"
    type: "{{ type }}"
    command_options: get_managementserver_pkg
  register: rslt
  tags: get_particular_managementserver_pkg

- name: update managementserver on LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    action: "{{ action }}"
    fixids: "{{ fixids }}"
    command_options: update_managementserver_pkg
  register: rslt
  tags: update_managementserver_pkg
