---
# tasks file for lenovo.lxca-config

- name: Reading Compliance Rules
  include_vars:
    file: config_pattern_import.yml
    name: pattern_update_dict
  when: read_from_file == 'true'
  tags: configpatterns


- name: get configpatterns data from LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    id: "{{ id }}"
    endpoint: "{{ endpoint }}"
    restart: "{{ restart }}"
    type: "{{ type }}"
    pattern_update_dict: "{{ pattern_update_dict }}"
    command_options: configpatterns
  register: rslt
  tags:
     configpatterns

- name: get configprofiles data from LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    id: "{{ id }}"
    name: "{{ name }}"
    endpoint: "{{ endpoint}}"
    restart: "{{ restart }}"
    action: "{{ action }}"
    powerdown: "{{ powerdown }}"
    resetimm: "{{ resetimm }}"
    force: "{{ force }}"
    command_options: configprofiles
  register: rslt
  tags:
     configprofiles


- name: get configtargets data from LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    id: "{{ id }}"
    command_options: configtargets
  register: rslt
  tags:
     configtargets

- block:
  - name: Managing given endpoint
    pylxca_module:
      login_user: "{{ lxca_user }}"
      login_password: "{{ lxca_password }}"
      auth_url: "{{ lxca_url }}"
      endpoint_ip: "{{ endpoint_ip }}"
      user: "{{ user }}"
      password: "{{ password }}"
      recovery_password: "{{ recovery_password }}"
      force: "{{ force }}"
      command_options: manage
    register: rslt_job
  - debug:
      var: rslt_job
  - name: Check manage job submission
    assert:
      that:
       -  " 'Success' in rslt_job.msg"

  - name: Polling for Status of Manage Operation
    pylxca_module:
      command_options: manage_status
      login_user: "{{ lxca_user }}"
      login_password: "{{ lxca_password }}"
      auth_url: "{{ lxca_url }}"
      jobid: "{{ rslt_job.result }}"
    register: result
    until: result.result.progress == 100.0
    retries: 20
    delay: 15

  - debug:
      var: result.result.progress
  tags:
    manage

- block:
  - name: Unmanaging given endpoint
    pylxca_module:
      login_user: "{{ lxca_user }}"
      login_password: "{{ lxca_password }}"
      auth_url: "{{ lxca_url }}"
      endpoint_ip: "{{ endpoint_ip }}"
      force: "{{ force }}"
      command_options: unmanage
    register: rslt_job
  - debug:
      var: rslt_job
  - name: Check submission of Unmanage job
    assert:
      that:
        - " 'Success' in rslt_job.msg"

  - name: Polling for Status of UnManage Operation
    pylxca_module:
      command_options: unmanage_status
      login_user: "{{ lxca_user }}"
      login_password: "{{ lxca_password }}"
      auth_url: "{{ lxca_url }}"
      jobid: "{{ rslt_job.result }}"
    register: result
    until: result.result.progress == 100.0
    retries: 20
    delay: 15

  - debug:
      var: result.result.progress
  tags:
    unmanage

- name: get updaterepo data from LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    repo_key: "{{ repo_key }}"
    action: "{{ action }}"
    machine_type: "{{ machine_type }}"
    scope: "{{ scope }}"
    fixids: "{{ fixids }}"
    file_type: "{{ file_type }}"
    command_options: updaterepo
  register: rslt
  tags:
     updaterepo

- name: Updating Firmware of device from LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    mode: "{{ mode}}"
    action: "{{ action }}"
    cmm: "{{ cmm }}"
    switch: "{{ switch }}"
    server: "{{ server }}"
    storage: "{{ storage }}"
    command_options: update_firmware
  register: rslt
  tags:
     update_firmware

- name: Getting Firmware Update Status from LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    command_options: update_firmware_query_status
  register: rslt
  tags:
     query_update_status

- name: Getting Updatable Components from LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    command_options: update_firmware_query_comp
  register: rslt
  tags:
     query_update_comp

- name: Get or Apply updatepolicy to device from LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    policy_info: "{{ policy_info}}"
    policy_name: "{{ policy_name}}"
    policy_type: "{{ policy_type}}"
    uuid: "{{ uuid }}"
    jobid: "{{ jobid }}"
    command_options: updatepolicy
  register: rslt
  tags:
     updatepolicy
