- name: Testing pylxca module
  hosts: server2
  tasks:
    - name: capture connect command
      pylxca_module:
        command_options: connect
        login_user: USERID
        login_password: CME44ibm
#        auth_url: https://10.241.53.171
        auth_url: https://10.243.14.80
        command_options: chassis
      register: conn
    - debug:
        var: conn

